package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Impianto generated by hbm2java
 */
@Entity
@Table(name = "t_impianto")
public class Impianto implements java.io.Serializable {

	private Integer impiantoId;
	@JsonBackReference("consistenza.impiantos")
	private Consistenza consistenza;
	private Typeimpianto typeimpianto;
	@JsonManagedReference("impianto.interventos")
	private Set<Intervento> interventos = new HashSet<Intervento>(0);
	
	public Impianto() {
	}

	public Impianto(Typeimpianto typeimpianto){
		this.typeimpianto = typeimpianto;
	}
	
	public Impianto(Consistenza consistenza, Typeimpianto typeimpianto,
			Set<Intervento> interventos) {
		this.consistenza = consistenza;
		this.typeimpianto = typeimpianto;
		this.interventos = interventos;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "impiantoId", unique = true, nullable = false)
	public Integer getImpiantoId() {
		return this.impiantoId;
	}

	public void setImpiantoId(Integer impiantoId) {
		this.impiantoId = impiantoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consistenzaId")
	public Consistenza getConsistenza() {
		return this.consistenza;
	}

	public void setConsistenza(Consistenza consistenza) {
		this.consistenza = consistenza;
	}

	@ManyToOne
	@JoinColumn(name = "typeImpiantoId")
	public Typeimpianto getTypeimpianto() {
		return this.typeimpianto;
	}

	public void setTypeimpianto(Typeimpianto typeimpianto) {
		this.typeimpianto = typeimpianto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impianto", cascade={CascadeType.ALL})
	public Set<Intervento> getInterventos() {
		return this.interventos;
	}

	public void setInterventos(Set<Intervento> interventos) {
		this.interventos = interventos;
	}

	public void linkBidirectionalAassociations(){
	
		for (Intervento intervento: this.getInterventos()) {
			intervento.setImpianto(this);
			intervento.linkBidirectionalAassociations();
		}
	}

	
	
}
