package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Intervento generated by hbm2java
 */
@Entity
@Table(name = "t_intervento")
public class Intervento implements java.io.Serializable {

	private Integer interventoId;
	@JsonBackReference("impianto.interventos")
	private Impianto impianto;
	private Typeintervento typeintervento;
	private Integer cadenzaMesi;
	private Integer numeroInterventi;
	@JsonManagedReference("intervento.attivitas")
	private Set<Attivita> attivitas = new HashSet<Attivita>(0);
	
	public Intervento() {
	}
	
	public Intervento(Typeintervento typeintervento){
		this.typeintervento = typeintervento;
	}

	public Intervento(Impianto impianto, Typeintervento typeintervento,
			Integer cadenzaMesi, Integer numeroInterventi,
			Set<Attivita> attivitas) {
		this.impianto = impianto;
		this.typeintervento = typeintervento;
		this.cadenzaMesi = cadenzaMesi;
		this.numeroInterventi = numeroInterventi;
		this.attivitas = attivitas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "interventoId", unique = true, nullable = false)
	public Integer getInterventoId() {
		return this.interventoId;
	}

	public void setInterventoId(Integer interventoId) {
		this.interventoId = interventoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "impianotId")
	public Impianto getImpianto() {
		return this.impianto;
	}

	public void setImpianto(Impianto impianto) {
		this.impianto = impianto;
	}

	@ManyToOne
	@JoinColumn(name = "typeInterventoId")
	public Typeintervento getTypeintervento() {
		return this.typeintervento;
	}

	public void setTypeintervento(Typeintervento typeintervento) {
		this.typeintervento = typeintervento;
	}

	@Column(name = "cadenzaMesi")
	public Integer getCadenzaMesi() {
		return this.cadenzaMesi;
	}

	public void setCadenzaMesi(Integer cadenzaMesi) {
		this.cadenzaMesi = cadenzaMesi;
	}

	@Column(name = "numeroInterventi")
	public Integer getNumeroInterventi() {
		return this.numeroInterventi;
	}

	public void setNumeroInterventi(Integer numeroInterventi) {
		this.numeroInterventi = numeroInterventi;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "intervento", cascade={CascadeType.ALL})
	public Set<Attivita> getAttivitas() {
		return this.attivitas;
	}

	public void setAttivitas(Set<Attivita> attivitas) {
		this.attivitas = attivitas;
	}

	public void linkBidirectionalAassociations(){
		for (Attivita attivita : this.getAttivitas()) {
			attivita.setIntervento(this);
		}
	}	

}
