package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Typemodalitapagamento generated by hbm2java
 */
@Entity
@Table(name = "t_typemodalitapagamento")
public class Typemodalitapagamento implements java.io.Serializable {

	private Integer typeModalitaPagamentoId;
	private String descrizione;
	private String codice;
	@JsonIgnore	
	private Set<Contratto> contrattos = new HashSet<Contratto>(0);

	public Typemodalitapagamento() {
	}

	public Typemodalitapagamento(String desrcizione) {
		this.descrizione = descrizione;
	}

	public Typemodalitapagamento(String descrizione, String codice,
			Set<Contratto> contrattos) {
		this.descrizione = descrizione;
		this.codice = codice;
		this.contrattos = contrattos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeModalitaPagamentoId", unique = true, nullable = false)
	public Integer getTypeModalitaPagamentoId() {
		return this.typeModalitaPagamentoId;
	}

	public void setTypeModalitaPagamentoId(Integer typeModalitaPagamentoId) {
		this.typeModalitaPagamentoId = typeModalitaPagamentoId;
	}

	@Column(name = "descizione", nullable = false, length = 50)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "codice", length = 5)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typemodalitapagamento")
	public Set<Contratto> getContrattos() {
		return this.contrattos;
	}

	public void setContrattos(Set<Contratto> contrattos) {
		this.contrattos = contrattos;
	}

}
