package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Typeintervento generated by hbm2java
 */
@Entity
@Table(name = "t_typeintervento")
public class Typeintervento implements java.io.Serializable {

	private Integer typeInterventoId;
	@JsonBackReference
	private Typeimpianto typeimpianto;
	private String descrizione;
	private String codice;
	@JsonIgnore
	private Set<Intervento> interventos = new HashSet<Intervento>(0);
	@JsonIgnore
	private Set<Typeattivita> typeattivitas = new HashSet<Typeattivita>(0);

	public Typeintervento() {
	}

	public Typeintervento(String descrizione) {
		this.descrizione = descrizione;
	}

	public Typeintervento(Typeimpianto typeimpianto, String descrizione,
			String codice, Set<Intervento> interventos,
			Set<Typeattivita> typeattivitas) {
		this.typeimpianto = typeimpianto;
		this.descrizione = descrizione;
		this.codice = codice;
		this.interventos = interventos;
		this.typeattivitas = typeattivitas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeInterventoId", unique = true, nullable = false)
	public Integer getTypeInterventoId() {
		return this.typeInterventoId;
	}

	public void setTypeInterventoId(Integer typeInterventoId) {
		this.typeInterventoId = typeInterventoId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "typeImpiantoId")
	public Typeimpianto getTypeimpianto() {
		return this.typeimpianto;
	}

	public void setTypeimpianto(Typeimpianto typeimpianto) {
		this.typeimpianto = typeimpianto;
	}

	@Column(name = "descrizione", nullable = false, length = 50)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "codice", length = 5)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeintervento")
	public Set<Intervento> getInterventos() {
		return this.interventos;
	}

	public void setInterventos(Set<Intervento> interventos) {
		this.interventos = interventos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeintervento")
	public Set<Typeattivita> getTypeattivitas() {
		return this.typeattivitas;
	}

	public void setTypeattivitas(Set<Typeattivita> typeattivitas) {
		this.typeattivitas = typeattivitas;
	}

}
