package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Typeattivita generated by hbm2java
 */
@Entity
@Table(name = "t_typeattivita")
public class Typeattivita implements java.io.Serializable {

	private Integer typeAttivitaId;
	@JsonBackReference
	private Typeintervento typeintervento;
	private String descrizione;
	private String codice;
	@JsonIgnore
	private Set<Attivita> attivitas = new HashSet<Attivita>(0);

	public Typeattivita() {
	}

	public Typeattivita(String descrizione) {
		this.descrizione = descrizione;
	}

	public Typeattivita(Typeintervento typeintervento, String descrizione,
			String codice, Set<Attivita> attivitas) {
		this.typeintervento = typeintervento;
		this.descrizione = descrizione;
		this.codice = codice;
		this.attivitas = attivitas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeAttivitaId", unique = true, nullable = false)
	public Integer getTypeAttivitaId() {
		return this.typeAttivitaId;
	}

	public void setTypeAttivitaId(Integer typeAttivitaId) {
		this.typeAttivitaId = typeAttivitaId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "typeInterventoId")
	public Typeintervento getTypeintervento() {
		return this.typeintervento;
	}

	public void setTypeintervento(Typeintervento typeintervento) {
		this.typeintervento = typeintervento;
	}

	@Column(name = "descrizione", nullable = false, length = 50)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "codice", length = 5)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeattivita")
	public Set<Attivita> getAttivitas() {
		return this.attivitas;
	}

	public void setAttivitas(Set<Attivita> attivitas) {
		this.attivitas = attivitas;
	}

}
