package com.mycompany.myapp.domain;

// Generated 18-nov-2013 12.05.48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Typeimpianto generated by hbm2java
 */
@Entity
@Table(name = "t_typeimpianto")
public class Typeimpianto implements java.io.Serializable {

	private Integer typeImpiantoId;
	@JsonBackReference
	private Typeconsistenza typeconsistenza;
	private String descrizione;
	private String codice;
	@JsonIgnore
	private Set<Impianto> impiantos = new HashSet<Impianto>(0);
	@JsonIgnore
	private Set<Typeintervento> typeinterventos = new HashSet<Typeintervento>(0);

	public Typeimpianto() {
	}

	public Typeimpianto(String descrizione) {
		this.descrizione = descrizione;
	}

	public Typeimpianto(Typeconsistenza typeconsistenza, String descrizione,
			String codice, Set<Impianto> impiantos,
			Set<Typeintervento> typeinterventos) {
		this.typeconsistenza = typeconsistenza;
		this.descrizione = descrizione;
		this.codice = codice;
		this.impiantos = impiantos;
		this.typeinterventos = typeinterventos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeImpiantoId", unique = true, nullable = false)
	public Integer getTypeImpiantoId() {
		return this.typeImpiantoId;
	}

	public void setTypeImpiantoId(Integer typeImpiantoId) {
		this.typeImpiantoId = typeImpiantoId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "typeConsistenzaId")
	public Typeconsistenza getTypeconsistenza() {
		return this.typeconsistenza;
	}

	public void setTypeconsistenza(Typeconsistenza typeconsistenza) {
		this.typeconsistenza = typeconsistenza;
	}

	@Column(name = "descrizione", nullable = false, length = 50)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "codice", length = 5)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeimpianto")
	public Set<Impianto> getImpiantos() {
		return this.impiantos;
	}

	public void setImpiantos(Set<Impianto> impiantos) {
		this.impiantos = impiantos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeimpianto")
	public Set<Typeintervento> getTypeinterventos() {
		return this.typeinterventos;
	}

	public void setTypeinterventos(Set<Typeintervento> typeinterventos) {
		this.typeinterventos = typeinterventos;
	}

}
